## tensor


In [2]:
import numpy as np

vector = np.array([1, 2, 3])  # 1D 向量
matrix_3x1 = vector.reshape(3, 1)  # 变成 3×1 矩阵

print(matrix_3x1)


[[1]
 [2]
 [3]]


In [3]:
matrix_T = matrix_3x1.T
print(matrix_T)
print(matrix_T.shape)
print(matrix_3x1.T.T)  # 逆转两次，得到原来的矩阵

[[1 2 3]]
(1, 3)
[[1]
 [2]
 [3]]


In [4]:
import numpy as np

# 定义两个相同形状的张量（矩阵）
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 加法
C_add = A + B

# 减法
C_sub = A - B

# 数乘
C_mul = 2 * A

print("A + B =\n", C_add)
print("A - B =\n", C_sub)
print("2 * A =\n", C_mul)


A + B =
 [[ 6  8]
 [10 12]]
A - B =
 [[-4 -4]
 [-4 -4]]
2 * A =
 [[2 4]
 [6 8]]



## 運算

In [5]:
import numpy as np
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])
print("A+B=\n",A+B)
print("A-B=\n",A-B)
print("3*A=\n",3*A)
print("A*B=\n",A*B)
import numpy as np

C_matmul = np.matmul(A, B)  # 正确的矩阵乘法
C_hadamard = A * B  # 逐元素相乘（Hadamard Product）

print("矩阵乘法 A @ B =\n", C_matmul)
print("Hadamard 乘法 A * B =\n", C_hadamard)


A+B=
 [[ 3  7]
 [11 15]]
A-B=
 [[1 1]
 [1 1]]
3*A=
 [[ 6 12]
 [18 24]]
A*B=
 [[ 2 12]
 [30 56]]
矩阵乘法 A @ B =
 [[22 34]
 [46 74]]
Hadamard 乘法 A * B =
 [[ 2 12]
 [30 56]]


In [6]:
## 用 NumPy 计算上面数学题的所有运算。生成一个 3×3 随机矩阵，并计算：
## 1.该矩阵与自身的点积2.该矩阵的 转置 与原矩阵的乘积
import numpy as np
A = np.random.rand(3, 3)
print("A =\n", A)
print("A @ A =\n", A @ A)
print("A.T @ A =\n", A.T @ A)

A =
 [[0.09271478 0.69008301 0.66174906]
 [0.75198085 0.0555715  0.46616198]
 [0.82186625 0.00738602 0.56115767]]
A @ A =
 [[1.07139446 0.10721754 0.75438994]
 [0.49463125 0.52546048 0.78511831]
 [0.54294985 0.57171111 0.86221024]]
A.T @ A =
 [[1.24953537 0.11183992 0.87309536]
 [0.11183992 0.4793573  0.48671182]
 [0.87309536 0.48671182 0.97011675]]


## 1.張量操作：請使用 numpy 建立一個 4 維張量，並取出其前兩個維度的切片。 

In [7]:
## 1.張量操作：請使用 numpy 建立一個 4 維張量
T = np.random.rand(2,2,2,2)   # 4D 張量
T_slice_2D = T[:, :, 0, 0]  # 只選取第一個 2x2 子矩陣
print("降維後張量形狀:", T_slice_2D.shape)  # (2,2)
print(T_slice_2D)  # 顯示選取的子矩陣
T_slice_specific = T[:, :, 0, :]  # 取出第3維索引 0 的所有數據
print("新的切片形狀:", T_slice_specific.shape)  # (2,2,2)
print(T_slice_specific)  # 顯示選取的子矩陣


降維後張量形狀: (2, 2)
[[0.95835573 0.20930656]
 [0.49774427 0.56705293]]
新的切片形狀: (2, 2, 2)
[[[0.95835573 0.31424596]
  [0.20930656 0.89349396]]

 [[0.49774427 0.50333139]
  [0.56705293 0.55567062]]]


## 2.矩陣乘積態（MPS）應用：嘗試用 MPS 近似一個 4x4x4 張量，看看誤差如何變化。

In [8]:
#2.矩陣乘積態（MPS）應用：嘗試用 MPS 近似一個 4x4x4 張量，看看誤差如何變化
# 隨機生成一個 4x4x4 張量
T0 = np.random.rand(4, 4, 4)
# 隨機生成三個矩陣                  
M1 = np.random.rand(4, 2)   # M1: 第一層矩陣
M2 = np.random.rand(2, 4, 2) # M2: 連結中間的矩陣
M3 = np.random.rand(2, 4)   # M3: 最後一層矩陣
# 張量重建
T_approx = np.einsum('ia,ajb,bc->ijc', M1, M2, M3)  # MPS 運算
# 檢查誤差
error = np.linalg.norm(T0 - T_approx)
print("誤差：", error)


誤差： 3.4619776364910093


##  交叉插值的示範

In [9]:
import numpy as np

# 生成一個 6x6 的矩陣
np.random.seed(0)
A = np.random.rand(6, 6)

# 選取某些行與列作為 pivots
rows = [0, 2, 4]  # Pivot rows
cols = [1, 3, 5]  # Pivot columns

# 取出 C, W, R
C = A[:, cols]  # 取出這些列
R = A[rows, :]  # 取出這些行
W = A[np.ix_(rows, cols)]  # 交叉區域

# 近似重建 A
A_approx = C @ np.linalg.pinv(W) @ R

# 計算誤差
error = np.linalg.norm(A - A_approx, 'fro')
print(f"矩陣交叉插值誤差: {error:.6f}")


矩陣交叉插值誤差: 2.405259


In [10]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

# 生成一個 10x10x10 的隨機函數張量
np.random.seed(42)
T = np.random.rand(10, 10, 10)

# 張量轉換為矩陣展開 (10, 100)
T_matrix = T.reshape(10, -1)

# 使用截斷 SVD 來近似
svd = TruncatedSVD(n_components=4)  # 只保留 3 個主要特徵
T_approx = svd.fit_transform(T_matrix) @ svd.components_

# 轉回 10x10x10 張量
T_approx = T_approx.reshape(10, 10, 10)

# 計算誤差
error = np.linalg.norm(T - T_approx)
print(f"TCI 近似誤差: {error:.6f}")


TCI 近似誤差: 6.468224


In [11]:
A = np.random.rand(8, 8)
def cross_interpolation(A, rank=2):
    """ 矩陣交叉插值 (Cross Interpolation, CI) 方法 """
    m, n = A.shape

    # 1. 選擇 rank 個行與列 (這裡隨機選擇)
    row_idx = np.random.choice(m, rank, replace=False)
    col_idx = np.random.choice(n, rank, replace=False)

    # 2. 取得交叉區塊 P
    P = A[np.ix_(row_idx, col_idx)]
    
    # 3. 取得 C 和 R
    C = A[:, col_idx]  # 取選定列
    R = A[row_idx, :]  # 取選定行

    # 4. 計算 U = P^(-1)
    P_inv = np.linalg.pinv(P)  # 使用偽逆以應對可能的數值問題

    # 5. 近似 A
    A_approx = C @ P_inv @ R

    return A_approx, row_idx, col_idx

# 執行 CI 方法
A_approx, row_idx, col_idx = cross_interpolation(A, rank=8)

# 顯示近似結果
print("近似矩陣 A_approx:")
print(A_approx)
# 計算誤差
error = np.linalg.norm(A - A_approx, ord='fro')
print(f"Frobenius Norm 誤差: {error:.5e}")

近似矩陣 A_approx:
[[0.30096357 0.70817209 0.0673506  0.58217046 0.34588306 0.62091552
  0.04574203 0.87153681]
 [0.97348897 0.96887786 0.74965183 0.13008624 0.7582632  0.02458692
  0.02212355 0.32361022]
 [0.48864319 0.77040742 0.68329538 0.44590271 0.27362667 0.9971245
  0.4261813  0.45138702]
 [0.16362382 0.79480955 0.69368223 0.22076961 0.08238105 0.6804993
  0.65451121 0.27325953]
 [0.95086356 0.15105789 0.4323348  0.94361592 0.41972732 0.63852595
  0.3975944  0.2742152 ]
 [0.98397765 0.40933401 0.8940992  0.22995461 0.2131047  0.03113408
  0.65166683 0.36852634]
 [0.86435825 0.47320991 0.96819343 0.18552552 0.86862317 0.77659685
  0.77092184 0.84478323]
 [0.76102399 0.62622032 0.13124488 0.03252618 0.92084785 0.61665031
  0.79653729 0.48152235]]
Frobenius Norm 誤差: 1.47137e-14



## 為什麼 TCI 只需要部分數據就能學習張量結構？
## 與 PCA 相比，TCI 的優勢與劣勢是什麼？
## 嘗試用 TCI 來近似一個更高維度的函數，例如 20x20x20 張量。

In [12]:
#1.為什麼 TCI 只需要部分數據就能學習張量結構？TCI可以反覆更新，直到誤差收斂
#與 PCA 相比，TCI 的優勢與劣勢是什麼？TCI 可以處理高維度數據，但是計算量較大，且需要調參，而 PCA 計算量小，但是只能處理低維度數據，且需要完整數據。
#嘗試用 TCI 來近似一個更高維度的函數，例如 20x20x20 張量。
import numpy as np
from sklearn.decomposition import TruncatedSVD
np.random.seed(47896512)
# 生成一個20x20x20 張量 的隨機函數張量
T=np.random.rand(20,20,20)
# 張量轉換為矩陣展開 (20, 400)
T_matrix = T.reshape(20, -1)  
# 使用截斷 SVD 來近似  
svd = TruncatedSVD(n_components=15)# 只保留 11 個主要特徵
T_approx = svd.fit_transform(T_matrix) @ svd.components_   
 # 轉回 20x20x20 張量
T_approx = T_approx.reshape(20, 20, 20)
# 計算誤差
error = np.linalg.norm(T - T_approx)
print(f"TCI 近似誤差: {error:.6f}")


TCI 近似誤差: 10.982050


In [13]:
for i in range(1, 21):
    svd = TruncatedSVD(n_components=i)
    T_approx = svd.fit_transform(T_matrix) @ svd.components_   
 # 轉回 20x20x20 張量
    T_approx = T_approx.reshape(20, 20, 20)
# 計算誤差
    error = np.linalg.norm(T - T_approx)
    print(f"TCI 近似誤差: {error:.7f}")

   

TCI 近似誤差: 25.0978852
TCI 近似誤差: 24.1737896
TCI 近似誤差: 23.2390187
TCI 近似誤差: 22.3152495
TCI 近似誤差: 21.3855198
TCI 近似誤差: 20.4565959
TCI 近似誤差: 19.4969665
TCI 近似誤差: 18.5273073
TCI 近似誤差: 17.5391298
TCI 近似誤差: 16.5334359
TCI 近似誤差: 15.5301475
TCI 近似誤差: 14.4659242
TCI 近似誤差: 13.3479064
TCI 近似誤差: 12.1552698
TCI 近似誤差: 10.9820503
TCI 近似誤差: 9.6773078
TCI 近似誤差: 8.1810646
TCI 近似誤差: 6.5443396
TCI 近似誤差: 4.4784457
TCI 近似誤差: 0.0000000


## real TCI

In [14]:
import numpy as np

# 生成一個 20x20x20 的張量
np.random.seed(47896512)
T = np.random.rand(20, 20, 20)
n=20
# 選擇 pivot 行列
rows = np.random.choice(20, n, replace=False)  # 隨機選 n 個 pivot 行
cols = np.random.choice(20, n, replace=False)  # 隨機選 n 個 pivot 列

# 取出 C, R, W
C = T[:, cols, :]  # 形狀: (20, 10, 20)
R = T[rows, :, :]  # 形狀: (10, 20, 20)
W = T[np.ix_(rows, cols, np.arange(20))]  # 形狀: (10, 10, 20)

# 逐個切片進行近似重建
T_approx = np.empty_like(T)
for k in range(T.shape[2]):
    Ck = C[:, :, k]         # 形狀: (20, 10)
    Wk = W[:, :, k]         # 形狀: (10, 10)
    Rk = R[:, :, k]         # 形狀: (10, 20)
    
    # 計算 Wk 的偽逆
    pinv_Wk = np.linalg.pinv(Wk)  # 形狀: (10, 10)
    
    # 重建該切片
    T_approx[:, :, k] = Ck @ pinv_Wk @ Rk

# 計算並印出誤差
error = np.linalg.norm(T - T_approx)
print(f"TCI 近似誤差: {error:.6f}")



TCI 近似誤差: 0.000000


##  3.1 生成低秩矩陣

In [15]:
import numpy as np

# 生成一個低秩矩陣 (rank-2)
m, n = 8, 8
U = np.random.rand(m, 2)  # 左矩陣
V = np.random.rand(2, n)  # 右矩陣
A = U @ V  # 低秩矩陣

print("原始矩陣 A:")
print(A)


原始矩陣 A:
[[0.77587306 0.8388079  0.58603833 0.7918035  0.56059093 0.44810269
  1.20266936 0.92399641]
 [0.89398613 0.83720728 0.77419213 1.02608462 0.68371066 0.55772099
  1.34172139 1.08150396]
 [0.66850849 0.85535326 0.40345924 0.56556702 0.44426592 0.34362761
  1.08141057 0.77885624]
 [0.25653771 0.20488477 0.24921995 0.32555126 0.20652923 0.17136612
  0.37297723 0.3149546 ]
 [0.67795493 0.839401   0.43061656 0.59822527 0.4587366  0.35746189
  1.08714247 0.79351505]
 [0.57203671 0.58138687 0.46042722 0.61637602 0.42413931 0.34224202
  0.8740875  0.68607246]
 [0.31645101 0.19014392 0.35532049 0.45664482 0.27305218 0.23143073
  0.43876818 0.39666566]
 [0.52784105 0.41507622 0.51774758 0.67554623 0.42684092 0.35467255
  0.76521314 0.64888219]]


## 3.2 矩陣交叉插值

In [16]:
np.random.seed(47896512)
T = np.random.rand(8, 8)
print("原始張量 T:")
print(T)

原始張量 T:
[[0.44547913 0.06006154 0.10415725 0.90626727 0.99492274 0.00228495
  0.79694964 0.41673096]
 [0.47995228 0.57931006 0.35666205 0.25582445 0.79498201 0.21552635
  0.17908936 0.14200637]
 [0.21590419 0.97964046 0.84394416 0.86136426 0.32076566 0.96357178
  0.46090256 0.71409378]
 [0.72606358 0.09340448 0.23219008 0.26367008 0.55251163 0.46374746
  0.02839732 0.33140086]
 [0.0235729  0.06193188 0.2307258  0.27738855 0.57066618 0.10268237
  0.07061079 0.38007721]
 [0.23295281 0.78243964 0.90622222 0.63073138 0.69345918 0.31217653
  0.83935614 0.56862306]
 [0.31178059 0.09004712 0.2542106  0.52572142 0.22141936 0.65199897
  0.94849556 0.21496246]
 [0.61736485 0.54867869 0.30539838 0.95138685 0.76435309 0.56593755
  0.66666494 0.5452999 ]]


In [17]:
import numpy as np


def cross_interpolation(A, rank=2):
    """ 矩陣交叉插值 (Cross Interpolation, CI) 方法 """
    m, n = A.shape

    # 1. 選擇 rank 個行與列 (這裡隨機選擇)
    row_idx = np.random.choice(m, rank, replace=False)
    col_idx = np.random.choice(n, rank, replace=False)

    # 2. 取得交叉區塊 P
    P = A[np.ix_(row_idx, col_idx)]
    
    # 3. 取得 C 和 R
    C = A[:, col_idx]  # 取選定列
    R = A[row_idx, :]  # 取選定行

    # 4. 計算 U = P^(-1)
    P_inv = np.linalg.pinv(P)  # 使用偽逆以應對可能的數值問題

    # 5. 近似 A
    A_approx = C @ P_inv @ R

    return A_approx, row_idx, col_idx

# 執行 CI 方法
A_approx, row_idx, col_idx = cross_interpolation(T, rank=8)

# 顯示近似結果
print("近似矩陣 A_approx:")
print(A_approx)

# 計算誤差
error = np.linalg.norm(A - A_approx, ord='fro')
print(f"Frobenius Norm 誤差: {error:.5e}")


近似矩陣 A_approx:
[[0.44547913 0.06006154 0.10415725 0.90626727 0.99492274 0.00228495
  0.79694964 0.41673096]
 [0.47995228 0.57931006 0.35666205 0.25582445 0.79498201 0.21552635
  0.17908936 0.14200637]
 [0.21590419 0.97964046 0.84394416 0.86136426 0.32076566 0.96357178
  0.46090256 0.71409378]
 [0.72606358 0.09340448 0.23219008 0.26367008 0.55251163 0.46374746
  0.02839732 0.33140086]
 [0.0235729  0.06193188 0.2307258  0.27738855 0.57066618 0.10268237
  0.07061079 0.38007721]
 [0.23295281 0.78243964 0.90622222 0.63073138 0.69345918 0.31217653
  0.83935614 0.56862306]
 [0.31178059 0.09004712 0.2542106  0.52572142 0.22141936 0.65199897
  0.94849556 0.21496246]
 [0.61736485 0.54867869 0.30539838 0.95138685 0.76435309 0.56593755
  0.66666494 0.5452999 ]]
Frobenius Norm 誤差: 3.27338e+00


## TCI error

In [18]:
from types  import SimpleNamespace
from typing import List, Tuple
import numpy as np
import matplotlib.pyplot as plt
def rook_pivoting(A: np.ndarray, k: int, nRookIter: int) -> Tuple[int, int, float]:
    max_iter = nRookIter
    rows = np.arange(k, A.shape[0])
    cols = np.arange(k, A.shape[1])
    i0, j0 = k, k
    err = abs(A[i0, j0])
    for _ in range(max_iter):
        # 找 column 最大值
        col_abs = np.abs(A[rows, j0])
        i_rel = np.argmax(col_abs)
        i_new = rows[i_rel]

        # 找 row 最大值
        row_abs = np.abs(A[i_new, cols])
        j_rel = np.argmax(row_abs)
        j_new = cols[j_rel]

        if i_new == i0 and j_new == j0:
            err = abs(A[i0, j0])
            break
        else:
            i0, j0 = i_new, j_new
            err = abs(A[i0, j0])
    return i0, j0, err



In [19]:
def cross_interpolation(A, rank, k=0, nRookIter=8): 
    """矩陣交叉插值 (Cross Interpolation, CI) 方法"""
    i0, j0, err = rook_pivoting(A, k, nRookIter)  # 用 k 而非 rank 當作起始索引
    # 這裡暫時只取單一 pivot
    row_idx = [i0]
    col_idx = [j0]
    # 取得交叉區塊 P
    P = A[np.ix_(row_idx, col_idx)]
    
    # 取得 C 和 R
    C = A[:, col_idx]  # 取選定的列
    R = A[row_idx, :]  # 取選定的行

    # 計算偽逆
    P_inv = np.linalg.pinv(P)

    # 近似 A
    A_approx = C @ P_inv @ R

    return A_approx, row_idx, col_idx


In [20]:
'''
import matplotlib.pyplot as plt
A = np.random.rand(8, 8)
A_approx, row_idx, col_idx = cross_interpolation(A, rank=7, k=0, nRookIter=1)

error = np.linalg.norm(A - A_approx, ord='fro')
print(f"Frobenius Norm 誤差: {error:.5e}")
print("擬和",A_approx)
print("原始",A)
nRookIters = range(1, 20)
errors = []

for nRookIter in nRookIters:
    A_approx, _, _ = cross_interpolation(A, rank=7,nRookIter=nRookIter)
    error = np.linalg.norm(A - A_approx, ord='fro')
    errors.append(error)

plt.plot(nRookIters, errors, marker='o')
plt.xlabel('nRookIter')
plt.ylabel('Frobenius Norm Error')
plt.title('Error vs. nRookIter for Cross Interpolation')
plt.grid(True)
plt.show()
'''


'\nimport matplotlib.pyplot as plt\nA = np.random.rand(8, 8)\nA_approx, row_idx, col_idx = cross_interpolation(A, rank=7, k=0, nRookIter=1)\n\nerror = np.linalg.norm(A - A_approx, ord=\'fro\')\nprint(f"Frobenius Norm 誤差: {error:.5e}")\nprint("擬和",A_approx)\nprint("原始",A)\nnRookIters = range(1, 20)\nerrors = []\n\nfor nRookIter in nRookIters:\n    A_approx, _, _ = cross_interpolation(A, rank=7,nRookIter=nRookIter)\n    error = np.linalg.norm(A - A_approx, ord=\'fro\')\n    errors.append(error)\n\nplt.plot(nRookIters, errors, marker=\'o\')\nplt.xlabel(\'nRookIter\')\nplt.ylabel(\'Frobenius Norm Error\')\nplt.title(\'Error vs. nRookIter for Cross Interpolation\')\nplt.grid(True)\nplt.show()\n'

## TCI with  SVD

In [32]:
np.random.seed(47896512)
T = np.random.rand(8, 8)
# SVD 分解
U, S, Vt = np.linalg.svd(T)

# 顯示奇異值
print("奇異值 S:")
print(S)

# 計算能量累積
energy_ratio = np.cumsum(S) / np.sum(S)
print("奇異值能量累積比率:")
print(energy_ratio)

def low_rank_approximation(A, rank):
    """ 透過 SVD 降維來建立低秩矩陣 """
    U, S, Vt = np.linalg.svd(A)
    S[rank:] = 0  # 只保留前 rank 個奇異值
    return U @ np.diag(S) @ Vt

# 降維到 rank=4
T_low_rank = low_rank_approximation(T, rank=4)

# 執行 CI 方法
A_approx, row_idx, col_idx = cross_interpolation(T_low_rank, rank=8)
A_approx_B, row_idx_B, col_idx_B = cross_interpolation(T, rank=8)
# 計算誤差
error_after = np.linalg.norm(T_low_rank - A_approx, ord='fro')
error_before = np.linalg.norm(T - A_approx_B, ord='fro')
print(f"降維前矩陣的 CI 近似誤差: {error_before:.5e}")
print(f"降維後矩陣的 CI 近似誤差: {error_after:.5e}")



奇異值 S:
[3.95287876 1.24380494 0.94162248 0.78930132 0.50966789 0.38069747
 0.20605066 0.0525982 ]
奇異值能量累積比率:
[0.4894223  0.64342294 0.76000912 0.85773579 0.92083988 0.96797561
 0.9934876  1.        ]
降維前矩陣的 CI 近似誤差: 3.41233e+00
降維後矩陣的 CI 近似誤差: 3.27609e+00


## tci by max min


In [22]:
import numpy as np
from types import SimpleNamespace
from typing import Tuple

# 生成一個 20x20x20 的張量
np.random.seed(47896512)
T = np.random.rand(20, 20, 20)

class TCI:
    def __init__(self, tensor: np.ndarray, rank: int = 10, pivoting: str = "rook", nRookIter: int = 3):
        """
        初始化 TCI 類別
        :param tensor: 需要近似的 3D 張量
        :param rank: 需要選取的 pivot 數量
        :param pivoting: 使用的選擇策略 (目前只支援 rook)
        :param nRookIter: rook pivoting 最大迭代次數
        """
        self.T = tensor
        self.rank = rank
        self.param = SimpleNamespace(nRookIter=nRookIter)
        self.m, self.n, self.p = tensor.shape

    def rook_pivoting(self, A: np.ndarray, k: int) -> Tuple[int, int, float]:
        """
        Rook pivoting: 透過最大值選擇最佳 pivot 行列
        """
        max_iter = self.param.nRookIter
        rows = np.arange(k, A.shape[0])
        cols = np.arange(k, A.shape[1])
        i0, j0 = k, k
        err = abs(A[i0, j0])

        for _ in range(max_iter):
            # 找列中的最大值
            col_abs = np.abs(A[rows, j0])
            i_rel = np.argmax(col_abs)
            i_new = rows[i_rel]
            max_col = col_abs[i_rel]

            # 找行中的最大值
            row_abs = np.abs(A[i_new, cols])
            j_rel = np.argmax(row_abs)
            j_new = cols[j_rel]
            max_row = row_abs[j_rel]

            if i_new == i0 and j_new == j0:
                err = abs(A[i0, j0])
                break
            else:
                i0, j0 = i_new, j_new
                err = abs(A[i0, j0])

        return i0, j0, err

    def select_pivots(self):
        """
        使用 rook pivoting 來選擇最佳 pivot 行與列
        """
        A_2D = np.mean(self.T, axis=2)  # 先對第三維度取均值，變成 2D 矩陣來選擇 pivots
        row_idx, col_idx = [], []

        for k in range(self.rank):
            i0, j0, _ = self.rook_pivoting(A_2D, k)
            row_idx.append(i0)
            col_idx.append(j0)
        
        return np.array(row_idx), np.array(col_idx)

    def compute_tci(self):
        """
        執行 TCI 演算法
        """
        # 透過 rook pivoting 選取最好的 pivot 行與列
        rows, cols = self.select_pivots()

        # 取出 C, W, R
        C = self.T[:, cols, :]  # (20, 10, 20) 取選定列
        R = self.T[rows, :, :]  # (10, 20, 20) 取選定行
        W = self.T[np.ix_(rows, cols, np.arange(self.p))]  # (10, 10, 20) 交叉區域 (核心)

        # 修正 W_inv 的維度確保其適用於矩陣乘法
        W_inv = np.linalg.pinv(W.reshape(10, 10 * self.p)).reshape(10, 10, self.p)

        # 近似重建: C (20, 10, 20) * W_inv (10, 10, 20) * R (10, 20, 20)
        T_approx = np.einsum("ijk,jlk,lmk->imk", C, W_inv, R)

        return T_approx, rows, cols


In [23]:
# 初始化 TCI 類別
tci = TCI(T, rank=10,nRookIter=10)

# 計算 TCI
T_approx, selected_rows, selected_cols = tci.compute_tci()

# 計算誤差
error = np.linalg.norm(T - T_approx)
print(f"TCI 近似誤差 (Frobenius Norm): {error:.6f}")
print(f"選擇的 pivot 行索引: {selected_rows}")
print(f"選擇的 pivot 列索引: {selected_cols}")


TCI 近似誤差 (Frobenius Norm): 49.389889
選擇的 pivot 行索引: [11 16 16 16 16 19 18  9 11 19]
選擇的 pivot 列索引: [ 8  4  4  4  4 19 12 11  8 19]


## error圖片

In [24]:
# 初始化 TCI 類別
tci = TCI(T, rank=10)

# 計算 TCI
T_approx, selected_rows, selected_cols = tci.compute_tci()

# 計算誤差
error = np.linalg.norm(T - T_approx)

In [25]:
nRookIters = range(1, 5)
errors = []
for nRookIter in nRookIters:
    tci = TCI(T, rank=10,nRookIter=nRookIter)
    T_approx, selected_rows, selected_cols = tci.compute_tci()
    error = np.linalg.norm(T - T_approx)
    errors.append(error)
    
'''
plt.plot(ranks, errors, marker='o')
plt.xlabel('Rank')
plt.ylabel('Frobenius Norm Error')
plt.title('Error vs. nRookIter for Cross Interpolation')
plt.grid(True)
plt.show()
'''

"\nplt.plot(ranks, errors, marker='o')\nplt.xlabel('Rank')\nplt.ylabel('Frobenius Norm Error')\nplt.title('Error vs. nRookIter for Cross Interpolation')\nplt.grid(True)\nplt.show()\n"

In [26]:
import numpy as np
import scipy.linalg

class prrLU:
    def __init__(self, A: np.ndarray, rank: int):
        """
        部分秩揭露 LU 分解
        :param A: 需要分解的矩陣
        :param rank: 近似的目標 rank
        """
        self.A = A.copy()
        self.rank = rank
        self.m, self.n = A.shape
        self.P = np.eye(self.m)
        self.L = np.zeros((self.m, self.rank))
        self.U = np.zeros((self.rank, self.n))
        self.row_idx = []
        self.col_idx = []

    def rook_pivoting(self, A, k):
        """
        使用 rook pivoting 選擇最大值來決定 pivot 行列
        """
        max_iter = 3
        rows = np.arange(k, A.shape[0])
        cols = np.arange(k, A.shape[1])
        i0, j0 = k, k
        err = abs(A[i0, j0])

        for _ in range(max_iter):
            # 找列中的最大值
            col_abs = np.abs(A[rows, j0])
            i_rel = np.argmax(col_abs)
            i_new = rows[i_rel]

            # 找行中的最大值
            row_abs = np.abs(A[i_new, cols])
            j_rel = np.argmax(row_abs)
            j_new = cols[j_rel]

            if i_new == i0 and j_new == j0:
                break
            else:
                i0, j0 = i_new, j_new
                err = abs(A[i0, j0])

        return i0, j0, err

    def compute_prrLU(self):
        """
        執行 prrLU 分解
        """
        A = self.A.copy()
        for k in range(self.rank):
            # 選擇最佳 pivot
            i0, j0, _ = self.rook_pivoting(A, k)
            self.row_idx.append(i0)
            self.col_idx.append(j0)

            # 交換 pivot 行與列
            A[[k, i0], :] = A[[i0, k], :]
            A[:, [k, j0]] = A[:, [j0, k]]

            # 計算 L 和 U
            self.L[k + 1:, k] = A[k + 1:, k] / A[k, k]
            self.U[k, k:] = A[k, k:]

            # 更新 A
            A[k + 1:, k + 1:] -= np.outer(self.L[k + 1:, k], self.U[k, k + 1:])

        return self.P, self.L, self.U, self.row_idx, self.col_idx

# 測試 prrLU
np.random.seed(42)
A = np.random.rand(8, 8)

prrlu = prrLU(A, rank=4)
P, L, U, row_idx, col_idx = prrlu.compute_prrLU()

# 驗證 prrLU 近似
A_approx = P @ L @ U
error = np.linalg.norm(A - A_approx)

print(f"prrLU 近似誤差: {error:.5e}")
print(f"選擇的 pivot 行索引: {row_idx}")
print(f"選擇的 pivot 列索引: {col_idx}")


prrLU 近似誤差: 3.37699e+00
選擇的 pivot 行索引: [1, 6, 6, 4]
選擇的 pivot 列索引: [3, 2, 2, 7]


## TCI + prrLU + Schur 補

In [27]:
import numpy as np
from scipy.linalg import lu

class TCI_Schur:
    def __init__(self, tensor: np.ndarray, rank: int = 10):
        """
        結合 prrLU、TCI 和 Schur 補
        :param tensor: 需要近似的 3D 張量
        :param rank: 需要選取的 pivot 數量
        """
        self.T = tensor
        self.rank = rank
        self.m, self.n, self.p = tensor.shape

    def compute_prrLU(self, A):
        """
        使用 prrLU 來選擇最佳 pivot 行與列
        :param A: 需要進行 prrLU 分解的 2D 矩陣
        :return: pivot 行與列索引
        """
        L, U = lu(A, permute_l=True)
        row_idx = np.argsort(np.abs(L[:, 0]))[-self.rank:]  # 挑選影響最大的行
        col_idx = np.argsort(np.abs(U[0, :]))[-self.rank:]  # 挑選影響最大的列
        return row_idx, col_idx

    def compute_schur(self, W, C, R):
        """
        計算 Schur 補來修正誤差
        """
        W_inv = np.linalg.pinv(W.reshape(self.rank, self.rank * self.p)).reshape(self.rank, self.rank, self.p)
        A_approx = np.einsum("ijk,jlk,lmk->imk", C, W_inv, R)
        residual = self.T - A_approx  # 計算殘差矩陣
        return residual

    def compute_tci_schur(self):
        """
        執行 TCI + prrLU + Schur 補
        """
        # 先取 T 在第三維上的平均，轉為 2D 矩陣來進行 prrLU
        A_2D = np.mean(self.T, axis=2)

        # 使用 prrLU 來選擇最好的 pivot 行與列
        rows, cols = self.compute_prrLU(A_2D)

        # 取出 C, R, W
        C = self.T[:, cols, :]  # (20, rank, 20) 取選定列
        R = self.T[rows, :, :]  # (rank, 20, 20) 取選定行
        W = self.T[np.ix_(rows, cols, np.arange(self.p))]  # (rank, rank, 20) 交叉區域

        # 計算 Schur 補
        S = self.compute_schur(W, C, R)

        # 計算 W 的偽逆
        W_inv = np.linalg.pinv(W.reshape(self.rank, self.rank * self.p)).reshape(self.rank, self.rank, self.p)

        # 近似重建 T + Schur 修正
        T_approx = np.einsum("ijk,jlk,lmk->imk", C, W_inv, R) 

        return T_approx, rows, cols

# 生成 20x20x20 張量
np.random.seed(47896512)
T = np.random.rand(10, 10, 10)

# 初始化 TCI_Schur 類別
tci_schur = TCI_Schur(T, rank=10)

# 計算 TCI + prrLU + Schur 補
T_approx, selected_rows, selected_cols = tci_schur.compute_tci_schur()

# 計算誤差
error = np.linalg.norm(T - T_approx)
print(f"TCI + prrLU 近似誤差 (Frobenius Norm): {error:.6e}")

print(f"選擇的 pivot 行索引: {selected_rows}")
print(f"選擇的 pivot 列索引: {selected_cols}")


TCI + prrLU 近似誤差 (Frobenius Norm): 1.692602e+01
選擇的 pivot 行索引: [5 7 4 9 0 6 3 8 2 1]
選擇的 pivot 列索引: [5 8 9 7 3 1 4 0 6 2]


##  Schur 補到底加了多少魔法??

In [28]:
import numpy as np
from scipy.linalg import lu

class TCI_Schur:
    def __init__(self, tensor: np.ndarray, rank: int = 10):
        """
        結合 prrLU、TCI 和 Schur 補
        :param tensor: 需要近似的 3D 張量
        :param rank: 需要選取的 pivot 數量
        """
        # 可考慮轉為 float32 減少精度，方便觀察數值誤差
        self.T = tensor.astype(np.float32)
        self.rank = rank
        self.m, self.n, self.p = self.T.shape

    def compute_prrLU(self, A):
        """
        使用 prrLU 來選擇最佳 pivot 行與列
        :param A: 需要進行 prrLU 分解的 2D 矩陣
        :return: pivot 行與列索引
        """
        # 注意：這裡採用 permute_l=True 回傳兩個矩陣
        L, U = lu(A, permute_l=True)
        row_idx = np.argsort(np.abs(L[:, 0]))[-self.rank:]  # 挑選影響最大的行
        col_idx = np.argsort(np.abs(U[0, :]))[-self.rank:]  # 挑選影響最大的列
        return row_idx, col_idx

    def compute_schur(self, W, C, R, W_inv):
        """
        計算 Schur 補來修正誤差
        """
        A_approx = np.einsum("ijk,jlk,lmk->imk", C, W_inv, R)
        residual = self.T - A_approx  # 計算殘差矩陣，也就是 Schur 補
        return residual

    def compute_tci_schur(self):
        """
        執行 TCI + prrLU + Schur 補，並回傳 Schur 補 S 以便分析其貢獻
        """
        # 先取 T 在第三維上的平均，轉為 2D 矩陣來進行 prrLU
        A_2D = np.mean(self.T, axis=2)

        # 使用 prrLU 來選擇最好的 pivot 行與列
        rows, cols = self.compute_prrLU(A_2D)

        # 取出 C, R, W
        C = self.T[:, cols, :]  # (m, rank, p)
        R = self.T[rows, :, :]  # (rank, n, p)
        W = self.T[np.ix_(rows, cols, np.arange(self.p))]  # (rank, rank, p)

        # 計算 W 的偽逆 (針對每個 p 進行偽逆計算)
        W_inv = np.linalg.pinv(W.reshape(self.rank, self.rank * self.p)).reshape(self.rank, self.rank, self.p)

        # 計算初始低階近似
        A_approx = np.einsum("ijk,jlk,lmk->imk", C, W_inv, R)
        # 計算 Schur 補 S
        S = self.compute_schur(W, C, R, W_inv)
        # 最終近似：原本的低階近似加上 Schur 補
        T_approx = A_approx + S

        # 為方便分析，也回傳 A_approx
        return T_approx, A_approx, S, rows, cols

# 測試用例：生成較低精度且規模較大的 tensor
np.random.seed(47896512)
T = np.random.rand(10, 10, 10).astype(np.float64)

# 初始化 TCI_Schur 類別
tci_schur = TCI_Schur(T, rank=10)

# 執行 TCI + prrLU + Schur 補
T_approx, A_approx, S, selected_rows, selected_cols = tci_schur.compute_tci_schur()

# 計算誤差
total_error = np.linalg.norm(T - T_approx)
schur_norm = np.linalg.norm(S)
approx_norm = np.linalg.norm(A_approx)
T_norm = np.linalg.norm(T)

print(f"TCI + prrLU + Schur 近似誤差 (Frobenius Norm): {total_error:.6e}")
print(f"初始低階近似 A_approx 的 Frobenius Norm: {approx_norm:.6e}")
print(f"Schur 補 S 的 Frobenius Norm: {schur_norm:.6e}")
print(f"Schur 補在 T 中的比例: {(schur_norm/T_norm)*100:.2f}%")
print(f"選擇的 pivot 行索引: {selected_rows}")
print(f"選擇的 pivot 列索引: {selected_cols}")


TCI + prrLU + Schur 近似誤差 (Frobenius Norm): 5.700633e-07
初始低階近似 A_approx 的 Frobenius Norm: 2.980450e+00
Schur 補 S 的 Frobenius Norm: 1.692602e+01
Schur 補在 T 中的比例: 93.32%
選擇的 pivot 行索引: [5 7 4 9 0 6 3 8 2 1]
選擇的 pivot 列索引: [5 8 9 7 3 1 4 0 6 2]


## schur and nr

In [29]:
import numpy as np
from scipy.linalg import lu

class TCI_Schur_Improved:
    def __init__(self, tensor: np.ndarray, rank: int = 10, pivoting: str = "rook",
                 nRookIter: int = 3, schur_weight: float = 0.1, regularization: float = 1e-5):
        """
        改進版 TCI + prrLU/rook pivoting + Schur 補
        :param tensor: 需要近似的 3D 張量
        :param rank: 需要選取的 pivot 數量
        :param pivoting: pivot 選擇策略，"rook" 或 "prrLU"
        :param nRookIter: rook pivoting 的最大迭代次數
        :param schur_weight: 控制 Schur 補的影響力 (介於 0 到 1)
        :param regularization: W 矩陣正則化參數，避免數值問題
        """
        self.m, self.n, self.p = tensor.shape
        self.rank = min(rank, min(self.m, self.n))  # 確保不超出矩陣維度
        self.T = tensor.astype(np.float64)
        self.pivoting = pivoting
        self.nRookIter = nRookIter
        self.schur_weight = schur_weight
        self.regularization = regularization

    def compute_prrLU(self, A):
        """
        使用 prrLU 來選擇最佳 pivot 行與列，這裡以行列範數做排序
        """
        row_norms = np.linalg.norm(A, axis=1)
        col_norms = np.linalg.norm(A, axis=0)
        row_idx = np.argsort(row_norms)[-self.rank:]
        col_idx = np.argsort(col_norms)[-self.rank:]
        return row_idx, col_idx

    def rook_pivoting(self, A: np.ndarray, k: int):
        """
        Rook pivoting：從 A 的子矩陣（從 k 開始）中選取一個 pivot，
        並透過 nRookIter 次迭代來改善選點品質
        """
        max_iter = self.nRookIter
        rows = np.arange(k, A.shape[0])
        cols = np.arange(k, A.shape[1])
        i0, j0 = k, k
        for _ in range(max_iter):
            i_new = rows[np.argmax(np.abs(A[rows, j0]))]
            j_new = cols[np.argmax(np.abs(A[i_new, cols]))]
            if i_new == i0 and j_new == j0:
                break
            i0, j0 = i_new, j_new
        pivot_val = abs(A[i0, j0])
        return i0, j0, pivot_val

    def select_pivots(self, A_2D):
        """
        根據 pivoting 策略選擇 pivot 行與列索引
        """
        if self.pivoting == "rook":
            row_idx = []
            col_idx = []
            for k in range(self.rank):
                i0, j0, _ = self.rook_pivoting(A_2D, k)
                row_idx.append(i0)
                col_idx.append(j0)
            return np.array(row_idx), np.array(col_idx)
        else:
            return self.compute_prrLU(A_2D)

    def compute_schur(self, W, C, R, W_inv):
        """
        計算 Schur 補，並以 schur_weight 調整其影響力
        """
        A_approx = np.einsum("ijk,jlk,lmk->imk", C, W_inv, R)
        residual = self.T - A_approx
        return self.schur_weight * residual

    def compute_tci_schur(self):
        """
        執行改進版 TCI + pivoting + Schur 補，回傳最終近似、初始近似、Schur 補、
        pivot 行與列索引，以及選點數量
        """
        # 將 tensor 沿第三維取均值，形成 2D 矩陣供 pivot 選取
        A_2D = np.mean(self.T, axis=2)
        rows, cols = self.select_pivots(A_2D)
        pivot_count = len(rows)

        # 擷取 C, R, W (注意各自的維度)
        C = self.T[:, cols, :]              # (m, rank, p)
        R = self.T[rows, :, :]               # (rank, n, p)
        W = self.T[np.ix_(rows, cols, np.arange(self.p))]  # (rank, rank, p)

        # 對 W 進行正則化以改善條件數
        W_reg = W + self.regularization * np.eye(self.rank)[:, :, np.newaxis]

        # 計算 W 的偽逆
        W_inv = np.linalg.pinv(W_reg.reshape(self.rank, self.rank * self.p)).reshape(self.rank, self.rank, self.p)

        # 計算初始低階近似
        A_approx = np.einsum("ijk,jlk,lmk->imk", C, W_inv, R)

        # 計算 Schur 補 (並加入權重)
        S = self.compute_schur(W, C, R, W_inv)

        # 得到最終 TCI 近似
        T_approx = A_approx + S

        return T_approx, A_approx, S, rows, cols, pivot_count

# === 測試程式 ===
if __name__ == '__main__':
    np.random.seed(47896512)
    T = np.random.rand(20, 20, 20)
    
    # 使用 "prrLU" 或 "rook" 都可以試試，這裡示範 prrLU 策略
    tci_schur_improved = TCI_Schur_Improved(T, rank=10, pivoting="prrLU",
                                              schur_weight=0.1, regularization=1e-5)
    T_approx, A_approx, S, selected_rows, selected_cols, pivot_count = tci_schur_improved.compute_tci_schur()

    error = np.linalg.norm(T - T_approx)
    print(f"改進後 TCI + prrLU + Schur 近似誤差: {error:.6e}")
    print(f"選點數量: {pivot_count}")
    print(f"選擇的 pivot 行索引: {selected_rows}")
    print(f"選擇的 pivot 列索引: {selected_cols}")



改進後 TCI + prrLU + Schur 近似誤差: 4.435625e+01
選點數量: 10
選擇的 pivot 行索引: [18 11  1 12  3  9 16 19 14  6]
選擇的 pivot 列索引: [10  1 13  0  8 18 17  7 19  4]
